### ISSUE TITLE
Creality CR-10 Max.ini > nozzle_diameter = 0.6 ?

### ISSUE THREAD

**Issue by IHateNameStealers** [teachingtechYT/SuperSlicer#3]
Question about the "Creality CR-10 Max.ini" (in /printer) and the file "CR-10 Max 0.4mm layer height.ini" (in /print)

I used both settings for a small 3DBenchy test, and I noticed that the filament was being pushed to hard, and started skipping.
I'm using the 0.4 nozzle, but I noticed that in the file "Creality CR-10 Max.ini" the nozzle_diameter = 0.6
Should this not be set to 0.4 ??

**Comment by teachingtechYT** [comment]
It's called that because the layer height is 0.4mm instead of 0.2mm.
